In [1]:
'''
# -*- coding: utf-8 -*-
# @Author: Yeshwanth
# @Date: 2021-01-04 18:58:12
# @Last Modified by: Yeshwanth
# @Last Modified time: 2021-01-09 12:30:53
# @Title: To create a 3X3 matrix where elements ranging from 2 to 10
'''
import numpy as np
class CreateMatrix:
    def creating_matrix(self):
        matrix = np.arange(2,11).reshape(3,3)
        print(matrix)
if __name__ == "__main__":
    create_matrix = CreateMatrix()
    create_matrix.creating_matrix()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
